controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

auth:
    path: /auth
    methods: POST
    controller: App\Controller\AuthenticationController::login